### ISSUE TITLE
everything updated to latest, still freezing.

### ISSUE THREAD

**Issue by manaboy** [rock88/moonlight-nx#43]
hi guys, i'm on the latest version of atmosphere and switch off, with the latest version of moonlight after a few minutes, the screen would lock up but sound continues to play, (Dolphin emulator or any other stream games.) other times the sound would switch off and video stream continues, sometimes the switch would lock up and only the volume button work, power/sleep, and home button won't respond at all.

Any workaround to this? i am haveing to play remotely due to the covid lockdown, :(

thanks in advance

**Comment by niekmos** [comment]
same problem!

**Comment by manaboy** [comment]
The android Moonlight app does not suffer this problem, if the developers could please look into this issue's, it's more of a bug then an issue.


Regards

**Comment by manaboy** [comment]
I've found the problem, Moonlight-NX struggles in handling video/audio stream flow, frame drops causes it to crash when bandwidth drops, to test this so say set your bitrate to 7Mbps and you're resolution to 720p and start a stream, now move away from your AP and it'll either pixelate or completely freeze lock up by the time you make it to the garden.

Another way to reproduce this is whilst streaming a game, run speedtest on another connected device.


Hope the developers could fix this, android version of Moonlight don't suffer this problem neither the window version.

**Comment by manaboy** [comment]
I've found the problem, Moonlight-NX struggles in handling video/audio stream flow, frame drops causes it to crash when bandwidth drops, to test this so say set your bitrate to 7Mbps and you're resolution to 720p and start a stream, now move away from your AP and it'll either pixelate or completely freeze lock up by the time you make it to the garden.

Another way to reproduce this is whilst streaming a game, run speedtest on another connected device.


Hope the developers could fix this, android version of Moonlight don't suffer this problem neither the window version.

> same problem!

For me I get a more stable play, least crashing with the following setting, 720p 60Fps, H264, 5.0Mbps, mouse click set to on, 4 decoder thread, and use streaming optimal playable settings on.

This is with my pc connected to my Virgin media box via ethernet cable, and my switch connected to my VM modem in forced 5G. Stream is stable when connecting my switch to my 4g phones hotspot. I've got Virgin media 200Mbit fibre optic broadband. And my sim is also Virgin media. 


Hope this helps

**Comment by sebbe1985** [comment]
I've been having the exact same issues since the beginning. Picture freezes after a couple of minutes play. When running the android client on the Switch, it works perfectly. Would be nice to have a fix for this because it's unplayable as it is now.. :(

**Comment by manaboy** [comment]
I think development on this is dead sadly, there is another version going about https://github.com/worleydl/moonlight-switch but that's still in eurly pre alpha stage, looks promising as it's constantly moving.

**Comment by masagrator** [comment]
> constantly moving

Last update: December 2018

It's almost december 2020, mate

**Comment by manaboy** [comment]
Indeed, the point is, it's another port, ol'rocky is busy so hasn't had the
chance to work on this.

On Saturday, November 21, 2020, masagrator <notifications@github.com> wrote:
> constantly moving
>
> Last update: December 2018
>
> It's almost december 2020, mate
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci5.googleusercontent.com/proxy/2ufs9XXPAxpBR7rk2-HBYQ7wyXWwkJPp3KTKvEjvnri6B2zesKhz9ht2bIcexwbYv5FBNPH2ETmYdkBoT1roNuJV84mbP0GdKIDm7ON5yNQ1xsk80qwuJ6J10tYsBjef79rNuir4eqAZgLx9AiwX6qOnQqi4tKU-3z0-Gx6SURSFseHgTbhCZIJ_Xi_9UhSh39SP2CbRVp08MCmhYsW7AMIdldl1TA_f6NA_4Phi9A=s0-d-e1-ft#https://github.com/notifications/beacon/ALWLHBTJEJME23XTWY2NKEDSQ7XD5A5CNFSM4TEK4BPKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOFONWVUA.gif>

**Comment by MrSnoozles** [comment]
Same problem here. It's definitely not completely unusable but a major annoyance.
The moonlight port is impressive anyway and I'm so happy it exists. Just wish the last few bugs would be ironed out.

**Comment by andytuinman3** [comment]
Same here. My stream just freezes every few minutes. For now unplayable. Let's hope Rock has more time in the near feature

**Comment by MrSnoozles** [comment]
@rock88 Is there anything we can do to support you on this - even if we can't debug it ourselves? Donations? Help you get some spare time otherwise?

**Comment by sebbe1985** [comment]
I would gladly contribute with something if this could be fixed!

**Comment by manaboy** [comment]
I feel your frustration guys it looks to be a system memory overflow or switch WiFi module error, someone suggested that removing the primary and secondary DNS that prevent connection to nintendo helps however, it's too risky as you risk getting your switch banned. Finally being able to stream play Street fighter v, SoulCalibur 6, eternal sonata via 360 emulator and Baten kaitos via dolphin emulator was a dream come true. Currently resorted to using a extending bluetooth controller with my Nexus 9, 8-inch tablet as this port is too unstable.

Hope Rocky gets to look at it soon, even a PayPal donation isn't a bad idea to give him some sort of incentive.

**Comment by MrSnoozles** [comment]
> someone suggested that removing the primary and secondary DNS that prevent connection to nintendo helps
I can confirm it does not. I'm not using the DNS and it's still crashing.

**Comment by manaboy** [comment]
Unfortunately not, anyone part of the development team can confirm if the main developers are still alive? I read somewhere that one of the 3 were Ill from covid..


Regards

**Comment by rock88** [comment]
Hi guys, I'm a alive and work with this project at free time. In the latest weeks I added few [new features](https://github.com/rock88/moonlight-nx/commits/master) and work on a stability, but app still can crash or freezes, so I will try to fix it 🙂

**Comment by sebbe1985** [comment]
> Hi guys, I'm a alive and work with this project at free time. In the latest weeks I added few [new features](https://github.com/rock88/moonlight-nx/commits/master) and work on a stability, but app still can crash or freezes, so I will try to fix it 🙂

That's amazing news! If we just could get rid of these freezes, this app will be the best thing that ever happened for the Switch 👌

**Comment by manaboy** [comment]
> Hi guys, I'm a alive and work with this project at free time. In the latest weeks I added few [new features](https://github.com/rock88/moonlight-nx/commits/master) and work on a stability, but app still can crash or freezes, so I will try to fix it 🙂

I'm glad your doing fine bro, was worried after someone said otherwise.

Thanks

**Comment by manaboy** [comment]
Just wanted to update this isses, it's been fixed in the latest 1.2.0 update. System updated to 12.0.2|AMS M.19.3E and everything working fine, no freezing.

Thanks Rock88

**Comment by RaasclartNinja** [comment]
I upgraded to the latest version yesterday and unfortunately still experienced the freezing issue. Video froze while audio stream continued.

**Comment by sebbe1985** [comment]
> I upgraded to the latest version yesterday and unfortunately still experienced the freezing issue. Video froze while audio stream continued.

Still freezing for me too, but I havent updated AMS and system to latest version yet.

**Comment by RaasclartNinja** [comment]
> > I upgraded to the latest version yesterday and unfortunately still experienced the freezing issue. Video froze while audio stream continued.
> 
> Still freezing for me too, but I havent updated AMS and system to latest version yet.

I'm running the latest 12.0.2 OS and Atmosphere 19.3

**Comment by manaboy** [comment]
Have you updated hekate? Also I've copied over the latestfusee primary.bin that's on the same download area as atmosphere, and one other step I did was to get the latest key files to decrypt latest games.

Try booting into hekate and loading the fusee primary payload and then  load homebrew browser by clicking on a game whilst holding down are to get full memeroy access. 

I'm sure it's working as I've not had it crush on me and I was one of those complaining about the freezing.

**Comment by RaasclartNinja** [comment]
> Have you updated hekate? Also I've copied over the latestfusee primary.bin that's on the same download area as atmosphere, and one other step I did was to get the latest key files to decrypt latest games.
> 
> Try booting into hekate and loading the fusee primary payload and then load homebrew launcher by clicking on a game whilst holding down R to get full memeroy access.
> 
> I'm sure it's working as I've not had it crush on me and I was one of those complaining about the freezing.

Yes, I updated everything as I accidentally updated to 12.0.2 and then Atmosphere stopped working so I did a clean setup with the latest everything. Still experienced the freezing issue, I imagine it’s the application not gracefully handling network latency or drops in the speed/connection.  But I’m not sure that’s the exact cause. 

I do always open in full memory mode as well.

**Comment by manaboy** [comment]
> > Have you updated hekate? Also I've copied over the latestfusee primary.bin that's on the same download area as atmosphere, and one other step I did was to get the latest key files to decrypt latest games.
> > Try booting into hekate and loading the fusee primary payload and then load homebrew launcher by clicking on a game whilst holding down R to get full memeroy access.
> > I'm sure it's working as I've not had it crush on me and I was one of those complaining about the freezing.
> 
> Yes, I updated everything as I accidentally updated to 12.0.2 and then Atmosphere stopped working so I did a clean setup with the latest everything. Still experienced the freezing issue, I imagine it’s the application not gracefully handling network latency or drops in the speed/connection. But I’m not sure that’s the exact cause.
> 
> I do always open in full memory mode as well.

Is your host pc connected via ethernet? This version of moonlight still has the issue where it can't handle anything above 10 Mbps.

Wednesday I'm going over to my brothers so going to be playing remotely over the internet, I hope it'll hold up, I'll keep this posted of any freezing issues.

Maybe completely delete and redownload moonlight NX.


Oh I forgot to add, I completely deleted moonlight NX then used HB App Store to download moonlight NX. Maybe that downloaded it to the default location fixed it. But I'm genuinely not getting any more issues

**Comment by cgutman** [comment]
I suspect the freezing issue is related to https://github.com/moonlight-stream/moonlight-common-c/issues/61 and the issue in libnx I discovered while debugging it https://github.com/switchbrew/libnx/issues/556
